/**
 * @module
 *
 * Fuzzy search capabilities
 */
import fuzzysort from "fuzzysort";
import { SEARCH_DISPLAY_LIMIT } from "../constants";
import {
	type FoodData,
	FoodType,
	type ProtocolData,
	type SearchResult,
} from "../types";

/**
 * Run fuzzy search against foods and/or protocol templates.
 *
 * For searchType "food": returns foods only (used for Food B search).
 * For searchType "protocol": returns protocols first, then foods (Food A search).
 *
 * @param query The user's search text
 * @param searchType "food" (foods only) or "protocol" (protocols + foods)
 * @param preparedFoods The array of prepared food objects (from fuzzySortPreparedFoods)
 * @param preparedProtocols The array of prepared protocol objects (from fuzzySortPreparedProtocols)
 * @returns Array of SearchResult objects
 */
export function performSearch(
	query: string,
	searchType: "food" | "protocol",
	preparedFoods: FoodData[],
	preparedProtocols: ProtocolData[],
): SearchResult[] {
	if (!query.trim()) return [];

	if (searchType === "food") {
		// Search foods only (for Food B)
		const results = fuzzysort.go(query, preparedFoods, {
			key: "prepared", // make use of the prepared property generated by fuzzysort.prepare(string)
			limit: SEARCH_DISPLAY_LIMIT,
			threshold: -10000,
		});
		// Filter out CAPSULE types and map to SearchResult
		return results
			.filter((r) => r.obj.Type !== FoodType.CAPSULE)
			.map((r) => ({ type: "food" as const, data: r.obj as FoodData }));
	} else {
		// Search both foods and protocols for Food A
		// Some searches here will never make it to the UI but that's ok, this is low cost
		const foodResults = fuzzysort.go(query, preparedFoods, {
			key: "prepared",
			limit: SEARCH_DISPLAY_LIMIT,
			threshold: -10000,
		});

		const protocolResults = fuzzysort.go(query, preparedProtocols, {
			key: "prepared",
			limit: SEARCH_DISPLAY_LIMIT,
			threshold: -10000,
		});

		// Combine and map to SearchResult
		const combined: SearchResult[] = [
			...protocolResults.map((r) => ({
				type: "protocol" as const,
				data: r.obj as ProtocolData,
			})),
			...foodResults.map((r) => ({
				type: "food" as const,
				data: r.obj as FoodData,
			})),
		];

		return combined;
	}
}
